logicalclocks/hops-hadoop-chef

- .kitchen.yml
- Berksfile
- attributes/default.rb
- metadata.rb
- providers/ndb.rb
- recipes/default.rb
- recipes/dn.rb
- recipes/install.rb
- recipes/jhs.rb
- recipes/ndb.rb
- recipes/nm.rb
- recipes/nn.rb
- recipes/ps.rb
- recipes/purge-ndb.rb
- recipes/purge.rb
- recipes/rm.rb
- recipes/wrap.rb
- release.sh
- templates/default/RM_EventAPIConfig.ini.erb
- templates/default/RT_EventAPIConfig.ini.erb
- templates/default/core-site.xml.erb
- templates/default/drop-and-recreate-hops-db.sh.erb
- templates/default/erasure-coding-site.xml.erb
- templates/default/hdfs-site.xml.erb
- templates/default/ndb.props.erb
- templates/default/root-drop-and-recreate-hops-db.sh.erb
- templates/default/yarn-site.xml.erb
Change to dot notation. Wrapped cookbook has been renamed to 'apache_hadoop'.
> Apache hadoop

- templates/default/yarn-site.xml.erb
changing yarn site to have the rm doing the proxy for the application master ui
> app master ui correction

- attributes/default.rb
Change the percentage of maximum AM resources so the VM can run more applications at the same time
> Fix AM max resources

- recipes/rm.rb
* Remove any previous conf file
* Source the template
> Fix capacity scheduler configuration file

- templates/default/hadoop-metrics2.properties.erb
change metrics period from 2 to 10 to not overload grafana with datapoints
https://hopshadoop.atlassian.net/browse/HOPSWORKS-74
> HOPSWORKS-74

- templates/default/yarn-site.xml.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-82
> HOPSWORKS-82

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- templates/default/yarn-env.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-103
> Add support for yarn-env.sh [HOPSWORKS-103]

- templates/default/yarn-env.sh.erb
Fix configuration attributes for RM NM heap size
> HOPSWORKS-112

- attributes/default.rb
- metadata.rb
- recipes/default.rb
Improve previous PR https://github.com/hopshadoop/hops-hadoop-chef/pull/44
> Improvements in copying libhopsnvml.so

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/nn.rb
- templates/default/core-site.xml.erb
- templates/default/ssl-server.xml.erb
RPC TLS configuration for Hops
https://hopshadoop.atlassian.net/browse/HOPSWORKS-122
> HOPSWORKS-122

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/install.rb
- recipes/nm.rb
- templates/default/yarn-site.xml.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-148
New attributes for hops-hadoop-chef for GPUs as well.
> Yarn shuffle jar fix and GPU settings updates [HOPSWORKS-148]

- recipes/default.rb
- recipes/install.rb
Move template of mapred-site to install recipe
https://hopshadoop.atlassian.net/browse/HOPSWORKS-155
> HOPSWORKS-155

- recipes/default.rb
- recipes/nn.rb
- templates/default/core-site.xml.erb
Add Hopsworks REST endpoint to core-site.xml
https://hopshadoop.atlassian.net/browse/HOPSWORKS-167
> HOPSWORKS-167

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/nn.rb
- templates/default/core-site.xml.erb
Remove reduntand properties and rename attribute
https://hopshadoop.atlassian.net/browse/HOPSWORKS-182
> HOPSWORKS-182

- recipes/default.rb
Apply ACL for top level directory as well so that hdfs and yarn user can access the certificates
> HOPSWORKS-73

- Vagrantfile
- attributes/default.rb
- metadata.rb
- recipes/install.rb
change user running yarn app to be different from the yarn user
> [HOPS-23] 

- recipes/default.rb
- recipes/install.rb
- recipes/ndb.rb
- recipes/rm.rb
Create rmyarn user and secure_hadoop group in install recipe
> Add RM user to certs acl

- recipes/default.rb
Change group of ssl-server.xml so that yarn containers can't localize it
https://hopshadoop.atlassian.net/browse/HOPSWORKS-253
> HOPSWORKS-253

- attributes/default.rb
- templates/default/hdfs-site.xml.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-361
> [HOPSWORKS-361] add small files configuration

- attributes/default.rb
https://hopshadoop.atlassian.net/browse/HOPS-134
> [HOPS-134] add version number for hops.sql

- recipes/nn.rb
Move creation here from livy-chef, as the user directory is also created in this cookbook
https://hopshadoop.atlassian.net/browse/HOPSWORKS-381
> [HOPSWORKS-381]  Create Glassfish HTTP logs dir in HDFS

- recipes/jhs.rb
https://github.com/hopshadoop/hops-testing/pull/20
> HOPSWORKS-382

- recipes/install.rb
Testing: https://github.com/hopshadoop/hops-testing/pull/30
> Install snappy library

- attributes/default.rb
- metadata.rb
- templates/default/yarn-site.xml.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-426
https://github.com/hopshadoop/hops-testing/pull/21
> [HOPSWORKS-426]

- attributes/default.rb
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-173
> [HOPS-173] Need to include all previous hops version in the hops.versions attribute

- Berksfile
- attributes/default.rb
- metadata.rb
- providers/hdfs_directory.rb
- recipes/default.rb
- recipes/format.rb
- recipes/install.rb
- recipes/nm.rb
- recipes/purge.rb
- recipes/rm.rb
- templates/default/hadoop-metrics2.properties.erb
- templates/default/yarn-site.xml.erb
Testing: https://github.com/hopshadoop/hops-testing/pull/46
> [HOPS-162] Enable LinuxContainerExecutor by default in Yarn

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/nn.rb
- templates/default/core-site.xml.erb
[HOPS-187]  Add Hops CRL validation properties
[HOPS-187]  Change port for Hopsworks endpoint
[HOPS-187]  Change name for the fetcher class attribute
https://hopshadoop.atlassian.net/browse/HOPS-187
> [HOPS-187]  Hops CRL validation configuration properties

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/nn.rb
- templates/default/core-site.xml.erb
- templates/default/hdfs-site.xml.erb
[HOPSWORKS-519]  Refactor Hops RPC TLS/CRL attributes
[HOPSWORKS-519]  Fix typo
https://hopshadoop.atlassian.net/browse/HOPSWORKS-519
> [HOPSWORKS-519]  Refactor Hops RPC TLS/CRL attributes

- Berksfile
- attributes/default.rb
- metadata.rb
- recipes/install.rb
- templates/default/mapred-site.xml.erb
JIRA: https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-507
Testing: https://github.com/hopshadoop/hops-testing/pull/75
> [HOPSWORKS-507] Add shuffle queue property in MapReduce config

- recipes/install.rb
- recipes/nm.rb
- templates/default/start-nm.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-536
> [HOPSWORKS-549] - FIxes for Horovod

- attributes/default.rb
- metadata.rb
- recipes/rm.rb
- templates/default/ssl-server.xml.erb
- templates/default/yarn-site.xml.erb
Configuration for RM certificates actor class
> [HOPS-291] Configuration for per-app X.509 certs

- attributes/default.rb
- recipes/install.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-587
> [HOPSWORKS-587] Chef recipe bugfixes

- attributes/default.rb
- metadata.rb
Testing: https://github.com/hopshadoop/hops-testing/pull/115
> [HOPSWORKS-599] Kafka tour broken because of HOPSWORKS-587

- attributes/default.rb
- metadata.rb
- templates/default/yarn-site.xml.erb
https://hopshadoop.atlassian.net/browse/HOPS-373
> [HOPS-373]  Configuration properties for RMApp certificate renewal

- attributes/default.rb
Testing: https://github.com/hopshadoop/hops-testing/pull/119
> [HOPSWORKS-605] Fix remote path for hops-examples and hops-util

- recipes/install.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-627
> [HOPSWORKS-627] remove managed home for some hadoop users (all except hdfs)

- attributes/default.rb
- metadata.rb
- templates/default/hdfs-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-645
> [HOPSWORKS-645]  Add configuration properties to enable DataNode datatransfer encryption

- attributes/default.rb
- metadata.rb
- templates/default/hdfs-site.xml.erb
[HOPSWORKS-645-amend]  Fix problematic Chef attributes
> [HOPSWORKS-645-amend]  Add missing comma

- libraries/default.rb
- recipes/default.rb
- recipes/rm.rb
Interpolate Hopsworks host both in default and rm recipe
> [HOPSWORKS-677] Fix hopsworks host attribute in yarn-site.xml

- templates/default/yarn-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-726
> [HOPSWORKS-726]  Change to Hopsworks CA V2 endpoints

- recipes/default.rb
- recipes/nn.rb
- templates/default/core-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-951
> [HOPSWORKS-951] Sqoop and airflow fixes

- attributes/default.rb
- metadata.rb
- recipes/install.rb
- recipes/purge.rb
adding hops/download_url as public attribute (metadata.rb) to point to hops artefacts download locations.
> HOPSWORKS-967

- attributes/default.rb
- libraries/default.rb
- metadata.rb
- recipes/default.rb
- recipes/dn.rb
- recipes/nm.rb
- recipes/nn.rb
- recipes/rm.rb
- templates/default/ssl-server.xml.erb
- templates/default/yarn-site.xml.erb
[HOPSWORKS-837]  Add JWT configuration
[HOPSWORKS-837]  Template ssl-server with jwt
[HOPSWORKS-837]  Get service JWT from kagent
[HOPSWORKS-837]  Fix typo
[HOPSWORKS-837]  Bump up Hops version
[HOPSWORKS-837]  Bump up Hops version
https://logicalclocks.atlassian.net/browse/HOPSWORKS-837
> [HOPSWORKS-837]  Refactor configuration properties for RM app security

- libraries/default.rb
- recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1066
> [HOPSWORKS-1066] Disable Hops TLS and JWT support if Hopsworks cookbook is not loaded

- attributes/default.rb
- files/default/renew_service_jwt.py
- libraries/default.rb
- metadata.rb
- recipes/install.rb
- templates/default/conda_renew_service_jwt.sh.erb
- templates/default/ssl-server.xml.erb
- templates/default/yarn-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1033
> [HOPSWORKS-1033] Redesign service JWT renewal protocol

- templates/default/hdfs-site.xml.erb
https://hopshadoop.atlassian.net/browse/HOPS-1329
> [HOPS-1329] Fix HTTP address in hdfs_le_descriptor table.

- recipes/_config.rb
- recipes/nm.rb
casecmp("..") returns a boolean, not an int.
> [HOPSWORKS-1095] append - casecmp fixes

- recipes/default.rb
- templates/default/core-site.xml.erb
> [HOPSWORKS-640] Flink

- attributes/default.rb
- metadata.rb
- recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1395
> [HOPSWORKS-1395] Change fetch CRL path

- attributes/default.rb
- metadata.rb
- templates/default/yarn-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1426
> [HOPSWORKS-1426] avoid using 100% CPU for yarn containers

- attributes/default.rb
- metadata.rb
- recipes/_config.rb
- recipes/default.rb
- recipes/ndb.rb
- templates/default/core-site.xml.erb
- templates/default/hdfs-site.xml.erb
- templates/default/ssl-server.xml.erb
- templates/default/yarn-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1425
> [HOPSWORKS-1425], [HOPS-1518] and make it possible to set a different version of ndb for hops-metadata

- templates/default/core-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1456
> [HOPSWORKS-1456] Fix templating Hopsworks security related properties

- recipes/jhs.rb
- recipes/nn.rb
- templates/default/historyserver.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1457
> [HOPSWORKS-1457] fix systemd script

- recipes/default.rb
- templates/default/core-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1464
> [HOPSWORKS-1464] set hdfs as default scheme and hopsfs as alt

- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1581
> [HOPSWORKS-1581] Touch hadoop.log with correct ownership and permission

- Karamelfile
- attributes/default.rb
- metadata.rb
- recipes/nm.rb
- templates/default/core-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1617
> [HOPSWORKS-1617] Azure resolve hostname fix

- files/default/renew_service_jwt.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1636
> [HOPSWORKS-1636] Change configuration property for service JWT in force renew script

- attributes/default.rb
- metadata.rb
- recipes/_config.rb
- recipes/install.rb
- recipes/ndb.rb
- recipes/nn.rb
- recipes/purge.rb
- templates/default/hdfs-site.xml.erb
Reverts logicalclocks/hops-hadoop-chef#190
> Revert "Revert "Added hopsfs-s3 support""

- templates/default/consul/nm-consul.hcl.erb
- templates/default/consul/nn-consul.hcl.erb
- templates/default/consul/rm-consul.hcl.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1405
> [HOPSWORKS-1405] More frequent health checks

- libraries/default.rb
- recipes/default.rb
- recipes/dn.rb
- recipes/jhs.rb
- recipes/nm.rb
- recipes/nn.rb
- recipes/rm.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1687
> [HOPSWORKS-1687] Allow Hops installation without Service Discovery

- templates/default/consul/nm-consul.hcl.erb
- templates/default/consul/nn-consul.hcl.erb
- templates/default/consul/rm-consul.hcl.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1718
> [HOPSWORKS-1718] Register services with passing health state

- recipes/nm.rb
- recipes/nn.rb
- recipes/rm.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1687
> [HOPSWORKS-1687] Do not template Consul health check scripts if service discovery is disabled

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/install.rb
- recipes/nm.rb
- templates/default/container-executor.cfg.erb
- templates/default/yarn-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1807
> [HOPSWORKS-1807] fix to be able to install only hops

- attributes/default.rb
- recipes/ndb.rb
- templates/default/flyway.conf.erb
- templates/default/ndb.props.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1825
> [HOPSWORKS-1825] Connect to local mysql server

- recipes/_config.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1865
> [HOPSWORKS-1865] Fix hops schemas for update from 1.2 to 1.3 to work

- attributes/default.rb
- libraries/default.rb
- metadata.rb
tests: https://github.com/logicalclocks/hops-testing-ee/pull/110
> [HOPSWORKS-1862] Fix cyclic dependency error

- attributes/default.rb
- libraries/default.rb
- metadata.rb
- providers/hdfs_directory.rb
- recipes/default.rb
- recipes/dn.rb
- recipes/docker_image.rb
- recipes/docker_registry.rb
- recipes/install.rb
- recipes/jhs.rb
- recipes/nm.rb
- recipes/nn.rb
- recipes/ps.rb
- recipes/rm.rb
- templates/default/consul/nn-health.sh.erb
- templates/default/core-site.xml.erb
- templates/default/ssl-server.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
> [HOPSWORKS-1657] System users x.509 v2

- templates/default/core-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
> [HOPSWORKS-1657] Template superuser material directory when either TLS is enabled or JWT

- attributes/default.rb
- metadata.rb
- templates/default/hdfs-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1859
> [HOPSWORKS-1859] make some ports configurable

- recipes/docker_registry.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1912
> [HOPSWORKS-1912] Do not download Docker image if it's already there

- recipes/default.rb
- recipes/docker.rb
- recipes/docker_image.rb
- recipes/docker_registry.rb
- templates/default/consul/registry-consul.hcl.erb
- templates/default/consul/registry-health.sh.erb
- templates/default/daemon.json.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1805
> [HOPSWORKS-1805] consul for docker registry

- recipes/nm.rb
- templates/default/yarn-site.xml.erb
Tests: 
https://github.com/logicalclocks/hops-testing-ee/pull/127
> [HOPSWORKS-1902] Add support for managed docker registries

- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1983
> [HOPSWORKS-1983] install bind-utils for rhel

- recipes/dn.rb
- recipes/jhs.rb
- recipes/nm.rb
- recipes/nn.rb
- recipes/ps.rb
- recipes/rm.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1977
> [HOPSWORKS-1977] use exising kagent/enabled, not kagent/test

- templates/default/datanode.service.erb
- templates/default/nodemanager.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1933
> [HOPSWORKS-1933] do not hang if consul not started

- attributes/default.rb
- metadata.rb
- templates/default/hdfs-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2022
> [HOPSWORKS-2022] make subtree-executor-limit configurable

- recipes/rm.rb
- templates/default/yarn-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2027
> [HOPSWORKS-2027] setup yarn exclude nodes file

- recipes/jhs.rb
- templates/default/historyserver.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2053
> [HOPSWORKS-2053] Historyserver should wait until NN Consul domain name becomes resolvable

- recipes/docker.rb
- templates/default/daemon.json.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2056
Fixes https://github.com/logicalclocks/hopsworks-cloud/issues/686
> [HOPSWORKS-2056] Override docker nameservers if localhost and debian-ish

- recipes/docker.rb
- templates/default/daemon.json.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2056
> [HOPSWORKS-2056] Override docker nameservers if localhost and debian-ish (#266)

- templates/default/datanode.service.erb
- templates/default/historyserver.service.erb
- templates/default/namenode.service.erb
- templates/default/nodemanager.service.erb
- templates/default/proxyserver.service.erb
- templates/default/resourcemanager.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Automatically restart failed systemd units

- templates/default/datanode.service.erb
- templates/default/historyserver.service.erb
- templates/default/namenode.service.erb
- templates/default/nodemanager.service.erb
- templates/default/proxyserver.service.erb
- templates/default/resourcemanager.service.erb
* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Wait before each restart
* [HOPSWORKS-2065] Fix burst
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Automatically restart failed systemd units (#272)

- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2072
> [HOPSWORKS-2072] Check if native binaries are present in Hops distribution

- recipes/nm.rb
- recipes/nn.rb
- recipes/rm.rb
- templates/default/namenode.service.erb
- templates/default/resourcemanager.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2080
> [HOPSWORKS-2080] Hops services should wait for Hopsworks if CRL validation is enabled

- templates/default/hdfs-site.xml.erb
https://hopshadoop.atlassian.net/browse/HOPS-1614
> [HOPS-1614] Fix quota calculation

- attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2174
> [HOPSWORKS-2174] issues attaching xattr to shared files

- templates/default/datanode.service.erb
- templates/default/historyserver.service.erb
- templates/default/namenode.service.erb
- templates/default/nodemanager.service.erb
- templates/default/resourcemanager.service.erb
fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-2292
> [HOPSWORKS-2292] remove systemd waiting mechanism

- attributes/default.rb
- metadata.rb
- templates/default/yarn-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2315
> [HOPSWORKS-2315] Template application key size

- templates/default/consul/nm-consul.hcl.erb
- templates/default/consul/nm-health.sh.erb
- templates/default/consul/rm-consul.hcl.erb
- templates/default/consul/rm-health.sh.erb
- templates/default/yarn-site.xml.erb
> [HOPSWORKS-2432] TLS for Resource Manager UI

- attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2551
> [HOPSWORKS-2551] Bump hops dependencies to 3.2.0.4-SNAPSHOT

- attributes/default.rb
- templates/default/ndb.props.erb
This reverts commit e657f1dfe5eab17b3e625a43bd57a1804fb4c0bd.
> Revert "[HOPS-1625] RonDB 21.04.0 (#311)"

- attributes/default.rb
- recipes/docker.rb
- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
> [HOPSWORKS-2578] Multi-disk nodes

- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2705
> [HOPSWORKS-2705] Do not try to create secure_group if it already exist

- recipes/docker.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
> [HOPSWORKS-2578] Fix resources to move Docker images to user data directory

- recipes/fuse_mnt.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-3058
> [HOPSWORKS-3058] unmount hopsfs-mount during upgrade

- attributes/default.rb
Fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-3076
> [HOPSWORKS-3076] Bumpup RonDB version

- attributes/default.rb
Fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-3076
> [HOPSWORKS-3076_2.5] Always use the same version as RonDB for Hops

- recipes/docker_registry.rb
Fix a centos bug - gets stuck on hops_docker_registry.rb, otherwise.
> [HOPSWORKS-2763] Opensearch 1.3.1

- recipes/default.rb
- recipes/rm.rb
- templates/default/consul/rm-health.sh.erb
- templates/default/core-site.xml.erb
https://hopsworks.atlassian.net/browse/HOPSWORKS-3149
testing: 
https://github.com/logicalclocks/hops-testing-ee/pull/532
> [HOPSWORKS-3149] Consul should only register the active resource manager

- attributes/default.rb
- metadata.rb
- templates/default/hdfs-site.xml.erb
Resolves https://hopsworks.atlassian.net/browse/HOPSWORKS-3339
> [HOPSWORKS-3339] Set and export disk utilization size retention for DN Cloud cache

- attributes/default.rb
- recipes/docker_registry.rb
Jira: https://hopsworks.atlassian.net/browse/HWORKS-311
> [HWORKS-311] Disable TLS1.0 and TLS1.1 for Docker registry

- attributes/default.rb
- metadata.rb
- templates/default/yarn-site.xml.erb
https://hopsworks.atlassian.net/browse/HOPSFS-41
> [HOPSFS-41] Export variable to require 2way auth in Yarn web UI

- attributes/default.rb
https://hopsworks.atlassian.net/browse/HOPSFS-42
> [HOPSFS-42] Update hops version to 3.2.0.8-RC0

- attributes/default.rb
- metadata.rb
- templates/default/daemon.json.erb
https://hopsworks.atlassian.net/browse/CLOUD-306
> [CLOUD-306] Export attribute to override default Docker daemon storage driver

- recipes/default.rb
- templates/default/core-site.xml.erb
* Allow flyingduck user to impersonate Hopsworks users
> [FSTORE-623] Fix Flyingduck deployment

- Karamelfile
- recipes/format.rb
[CLOUD-365] Command line returns with 1 instead of 0 as normally is done
https://hopsworks.atlassian.net/browse/CLOUD-365
[CLOUD-365]: https://hopsworks.atlassian.net/browse/CLOUD-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLOUD-365] Rollback deleted blocks from Cloud

- recipes/format.rb
https://hopsworks.atlassian.net/browse/CLOUD-408
> [CLOUD-408] Change ndb attribute

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/docker_cgroup.rb
- templates/default/nm-cgroup-fix.sh.erb
- templates/default/yarn-site.xml.erb
Add support in NodeManager for cgroup2
Also, adapt our cgroup scripts to cgroup2
https://hopsworks.atlassian.net/browse/CLOUD-430
> [CLOUD-430] Adapt to cgroup2

- attributes/default.rb
Reverts logicalclocks/hops-hadoop-chef#437
> Revert "[HOPSFS-67] Use -SNAPSHOT for ndb-metadata-dal"

- attributes/default.rb
Reverts logicalclocks/hops-hadoop-chef#439
> Revert "Revert "[HOPSFS-67] Use -SNAPSHOT for ndb-metadata-dal""

- recipes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-442
> [CLOUD-442] Add support for flyingduck on the cloud

- attributes/default.rb
- recipes/docker.rb
- recipes/docker_cgroup.rb
* Add attribute for docker cgroup parent
* PR review
> [HWORKS-512] Add attribute for docker cgroup parent

- recipes/nn.rb
- recipes/rm.rb
- templates/default/nn-waiter.sh.erb
- templates/default/rm-waiter.sh.erb
[CLOUD-583] Wait for ResourceManager
[CLOUD-583]: https://hopsworks.atlassian.net/browse/CLOUD-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLOUD-583] Wait for NameNode

- recipes/_config.rb
- templates/default/rm-waiter.sh.erb
- templates/default/yarn-site.xml.erb
[HWORKS-612] Follow redirects on waiter script
[HWORKS-612]: https://hopsworks.atlassian.net/browse/HWORKS-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HWORKS-612] Correctly template RM HA properties

- attributes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-620
> [HWORKS-620] Bump Hops version in preparation for 3.3.0 release

- templates/default/hadoop-env.sh.erb
- templates/default/yarn-site.xml.erb
https://hopsworks.atlassian.net/browse/HWORKS-658
> [HWORKS-658] Set Java tmpdir property

- providers/tours.rb
Fixes https://hopsworks.atlassian.net/browse/FSTORE-857
> [FSTORE-857] Remove version from hsfs utils to avoid upgrade issues

- attributes/default.rb
- metadata.rb
- recipes/docker_registry.rb
https://hopsworks.atlassian.net/browse/HWORKS-768
> [HWORKS-768] Attribute to mount arbitrary volumes to Docker registry container

- recipes/docker_registry.rb
https://hopsworks.atlassian.net/browse/HWORKS-779
> [HWORKS-779] Use host network instead of bridge

- attributes/default.rb
- libraries/default.rb
- metadata.rb
- recipes/dn.rb
- recipes/install.rb
- recipes/nm.rb
- recipes/nn.rb
- recipes/rm.rb
- templates/default/core-site.xml.erb
- templates/default/ssl-server.xml.erb
- templates/default/yarn-site.xml.erb
https://hopsworks.atlassian.net/browse/HOPSFS-125
> [HOPSFS-125] Template API key instead of service JWT

- templates/default/yarn-site.xml.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-97
> [CLOUD-97] Add support for GCR/GKE

- attributes/default.rb
HOPSFS-151 Bump Hops Hadoop Version to 3.2.0.13
> HOPSFS-151 Bump Hops Hadoop Version to 3.2.0.13

- attributes/default.rb
Bump test connector version- updates for JDBC support
> [FSTORE-920] Bump test connector version 

- recipes/install.rb
https://hopsworks.atlassian.net/browse/HWORKS-1191
> [HWORKS-1191] Split extracting the archive and symlinking

- recipes/install.rb
https://hopsworks.atlassian.net/browse/HWORKS-1191
> [HWORKS-1191] Do not chown if the installation already existed

- attributes/default.rb
RONDB-661 RonDB minor release 22.10.3
> RONDB-661 RonDB minor release 22.10.3

- attributes/default.rb
HOPSFS-161 Bump Hops Hadoop Version to 3.2.0.13-RC0
> HOPSFS-161 Bump Hops Hadoop Version to 3.2.0.13-RC0
