logicalclocks/hops-hadoop-chef

Berksfile

Branch 7_5 is merged and does not exist. Because of that there is a berks failure in the cookbook while vendor.

Reverting to master branch as 7_5 is merged.

---

templates/default/yarn-site.xml.erb

yarn.nodemanager.container-metrics.period-ms config parameter is not present in the yarn-site.xml file. This will allow to log more metrics to the influxdb

container-metrics.period-ms added

---

attributes/default.rb
metadata.rb
providers/ndb.rb
recipes/default.rb
recipes/install.rb
recipes/ndb.rb
recipes/nn.rb
templates/default/core-site.xml.erb
templates/default/hdfs-site.xml.erb

Create a hdfs supergroup, and add glassfish and hdfs users to it. Glassfish needs superuser permissions to perform log aggregation in Hopsworks. Livy and Hive users need to be able to do secure impersonation.

HOPSWORKS-175

---

recipes/default.rb
recipes/install.rb
recipes/nn.rb
templates/default/core-site.xml.erb

* Add yarn, rmyarn and hdfs users to certificates group and remove acl
* Put back acl for hdfs user on keystores, needed during deployment
* Fix syntax error
* Add jupyter user to super proxyusers
https://hopshadoop.atlassian.net/browse/HOPSWORKS-232

HOPSWORKS-232

---

attributes/default.rb

Remove unsupported TLS/SSL versions from the server configuration
https://hopshadoop.atlassian.net/browse/HOPS-258

[HOPS-258]  Remove unsupported TLS/SSL versions

---

attributes/default.rb
metadata.rb
templates/default/yarn-site.xml.erb

https://github.com/logicalclocks/hops-testing/pull/211
To cherry-pick to 0.6

[HOPSWORKS-771] Allow memory quota configuration in yarn

---

.gitignore
attributes/default.rb
metadata.rb

- Move spark-example and hops-util spark dependency attributes from hops-hadoop-chef to spark-chef

[HOPSWORKS-853] Feature Store Tour

---

attributes/default.rb
metadata.rb
recipes/default.rb
recipes/nn.rb
templates/default/core-site.xml.erb
templates/default/get-topology.sh.erb
templates/default/hadoop-metrics2.properties.erb
templates/default/hdfs-site.xml.erb
templates/default/topology.erb

Added LocationDomainId for nn and network topology based on the GCE availability zones (locationDomainIds)
Add attributes for handler count, hdfs quota, retry cache, and graphite
Tests: https://github.com/logicalclocks/hops-testing/pull/285
**Notes** 
* This pull request is dependent on the new changes in Karamel to assign a locationDomainId to each ip, however, it is backward compatible, if no locationDomainId is provided, it will use the default value 0.
* Availability Zone Awareness support is added to HopsFS v2.8.2.8

[HOPSWORKS-923] Availability Zone Awareness support for HopsFS

---

attributes/default.rb
metadata.rb
recipes/jhs.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-966
This is required when running Apache Sqoop as a project specific user. History server does not store any sensitive information and it is available anyway through a REST API

[HOPSWORKS-966]  Give 777 permission to MapReduce History Server dir

---

recipes/default.rb
templates/default/core-site.xml.erb

- serving user needs to be able to impersonate project_users

[HOPSWORKS-751] add support for serving sklearn models

---

recipes/default.rb
recipes/install.rb

Some applications need to be able to access Hadoop binaries and
configurations without being in the hadoop group. Grant read
access to everybody to non-sensitive files.

[HOPSWORKS-1162] Make Hadoop home readable for everybody

---

attributes/default.rb
recipes/install.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1588
Co-authored-by: Salman Niazi <salman@logicalclocks.com>

[HOPSWORKS-1588] Increased default Java heap size and DirectByteBuffer size to 1G (#181)

---

attributes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1666

[HOPSWORKS-1666] Enable NM detect hw capabilities by default

---

attributes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2090

[HOPSWORKS-2090] Bumpup docker.io version

---

attributes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2090

[HOPSWORKS-2090] Bumpup docker.io version (#281)

---

attributes/default.rb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-2287

[HOPSWORKS-2287] Bump up docker.io version for ubuntu

---

attributes/default.rb
recipes/docker.rb

An ubuntu upstream change removed the containerd version required by our Docker.
This is a temporary change before we solve HOPSWORKS-2647.
We distribute the .deb files for containerd, docker and runc.

[HOPSWORKS-2663] Fix docker installation on ubuntu 18.04

---

attributes/default.rb

Retrying failing applications has little value in the feature store context.
It confuses the users on the real cause of the error and potentially insert duplicated data.

[HOPSWORKS-2692] Disable Yarn application retry

---

attributes/default.rb
metadata.rb
templates/default/yarn-site.xml.erb

Expose Capacity scheduler attribute to configure user limit per queue
Resolves https://hopsworks.atlassian.net/browse/HOPSWORKS-3169

[HOPSWORKS-3169] Configure min user limit in Yarn capacity scheduler

---

attributes/default.rb
metadata.rb
templates/default/hdfs-site.xml.erb

we can no longer enable / disable small files using this property dfs.store.small.files.in.db. Small files are now controlled by a storage policy. If you set the storage policy to DB for a folder then the new files created in this folder will be stored in the database

[HOPSWORKS-3307] hops-hadoop-chef: remove unused params for small files

---

recipes/default.rb

Fixes https://hopsworks.atlassian.net/browse/HOPSWORKS-3334

[HOPSWORKS-3334] Discover Hopsworks port also when running fuse_mnt recipe and also use the default port instead of empty string

---

attributes/default.rb
metadata.rb
templates/default/hdfs-site.xml.erb

Resolves https://hopsworks.atlassian.net/browse/HOPSWORKS-3339

[HOPSWORKS-3339] Set and export disk utilization size retention for DN Cloud cache (#393)

---

attributes/default.rb

https://hopsworks.atlassian.net/browse/CLOUD-496

[CLOUD-496] Disable cgroup memory controller by default

---

attributes/default.rb
metadata.rb
templates/default/core-site.xml.erb
templates/default/namenode.service.erb
templates/default/resourcemanager.service.erb

[HOPSFS-124] Do not template empty truststore configuration
[HOPSFS-124] Relax - almost disable - restart limits when liveness watchdog is enabled because it is normal for a service to start and die immediately
[HOPSFS-124]: https://hopsworks.atlassian.net/browse/HOPSFS-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HOPSFS-124]: https://hopsworks.atlassian.net/browse/HOPSFS-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HOPSFS-124] Watchdog configuration

---

attributes/default.rb

HOPSFS-139 Bump Hops Hadoop Version to 3.2.0.12

HOPSFS-139 Bump Hops Hadoop Version to 3.2.0.12
